version: "3.7"
services:
  web:
    image: nginx
    ports:
      - "8081:443"
    configs:
      - source: nginx-config-ssl
        target: /etc/nginx/conf.d/ssl.conf
        mode: 0440
    secrets:
      - site.crt
      - site.key
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - php-fpm
    networks:
      - stack-net
  
  php-fpm:
    image: bitnami/php-fpm
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - stack-net
  
networks:
  stack-net:

configs:
  nginx-config-ssl:
    external: true

secrets:
  site.crt:
    external: true
  site.key:
    external: true

